name: midastouch
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- configargparse
- imageio
- imageio-ffmpeg
- matplotlib
- openblas-devel
- pip
- pyglet
- pyvista
- scikit-image
- scikit-learn
- tensorboard
- tqdm
- transforms3d
- suitesparse
- pip:
  - addict
  - antlr4-python3-runtime
  - anyio
  - argon2-cffi-bindings
  - argon2-cffi
  - asttokens
  - babel
  - backcall
  - beautifulsoup4
  - bleach
  - debugpy
  - defusedxml
  - deprecation
  - digit-interface
  - dill
  - entrypoints
  - executing
  - fastjsonschema
  - ffmpeg-python
  - freetype-py
  - gdown
  - git+https://github.com/suddhu/tacto.git@master
  - git+https://github.com/u1234x1234/pynanoflann.git@0.0.9
  - gitpython
  - gputil
  - hydra-core
  - ipykernel
  - ipython-genutils
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - json5
  - jsonschema
  - jupyter-client
  - jupyter-core
  - jupyter-packaging
  - jupyter-server
  - jupyterlab-pygments
  - jupyterlab-server
  - jupyterlab-widgets
  - jupyterlab
  - lxml
  - markupsafe
  - matplotlib-inline
  - mesh_to_sdf
  - mistune
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - ninja
  - notebook-shim
  - notebook
  - omegaconf
  - open3d
  - opencv-python
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - potpourri3d
  - prometheus-client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure-eval
  - pybind11
  - pycollada
  - pygments
  - pyopengl
  - PyQt5
  - pyquaternion
  - pyrender
  - pyrsistent
  - pytz
  - pyvistaqt
  - pyzmq
  - qtpy
  - rtree
  - seaborn
  - send2trash
  - sniffio
  - soupsieve
  - stack-data
  - terminado
  - tinycss2
  - tomlkit
  - traitlets
  - trimesh
  - urdfpy
  - wcwidth
  - webencodings
  - websocket-client
  - widgetsnbextension
  - yappi